"""empty message

Revision ID: 9ce2ffef67a9
Revises: 
Create Date: 2020-03-31 12:19:06.885654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ce2ffef67a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id_idx', table_name='sell')
    op.drop_table('sell')
    op.drop_table('role')
    op.drop_index('category_help_id_idx', table_name='question_answer')
    op.drop_index('user_id_idx', table_name='question_answer')
    op.drop_table('question_answer')
    op.drop_index('detail_id_idx', table_name='role_has_detail')
    op.drop_index('role_id_idx', table_name='role_has_detail')
    op.drop_table('role_has_detail')
    op.drop_table('sf_guard_user_group')
    op.drop_index('user_id_idx', table_name='category_contact')
    op.drop_table('category_contact')
    op.drop_table('wpsnk_usermeta')
    op.drop_index('order_resume_id_idx', table_name='order_item')
    op.drop_index('user_id_idx', table_name='order_item')
    op.drop_table('order_item')
    op.drop_index('comment_approved_date_gmt', table_name='wpsnk_comments')
    op.drop_table('wpsnk_comments')
    op.drop_index('product_id_idx', table_name='ask')
    op.drop_index('user_id_idx', table_name='ask')
    op.drop_table('ask')
    op.drop_index('user_id_idx', table_name='sf_guard_remember_key')
    op.drop_table('sf_guard_remember_key')
    op.drop_index('brand_id_idx', table_name='model_cat')
    op.drop_index('model_cat_id_idx', table_name='model_cat')
    op.drop_index('model_cat_sluggable_idx', table_name='model_cat')
    op.drop_index('user_id_idx', table_name='model_cat')
    op.drop_table('model_cat')
    op.drop_table('sf_guard_group_permission')
    op.drop_index('email_address', table_name='order_resume')
    op.drop_index('shipping_email_address', table_name='order_resume')
    op.drop_index('shipping_id_idx', table_name='order_resume')
    op.drop_index('user_id_idx', table_name='order_resume')
    op.drop_table('order_resume')
    op.drop_table('wpsnk_commentmeta')
    op.drop_table('detail')
    op.drop_index('attribute_sluggable_idx', table_name='attribute')
    op.drop_index('user_id_idx', table_name='attribute')
    op.drop_table('attribute')
    op.drop_index('link_direction', table_name='wpsnk_yoast_seo_links')
    op.drop_table('wpsnk_yoast_seo_links')
    op.drop_index('user_id_idx', table_name='sf_guard_forgot_password')
    op.drop_table('sf_guard_forgot_password')
    op.drop_index('name', table_name='sf_guard_group')
    op.drop_table('sf_guard_group')
    op.drop_table('wpsnk_term_relationships')
    op.drop_index('term_id_taxonomy', table_name='wpsnk_term_taxonomy')
    op.drop_table('wpsnk_term_taxonomy')
    op.drop_index('category_contact_id_idx', table_name='contact')
    op.drop_index('company_id_idx', table_name='contact')
    op.drop_index('user_id_idx', table_name='contact')
    op.drop_table('contact')
    op.drop_index('category_help_id_idx', table_name='category_help')
    op.drop_index('category_help_sluggable_idx', table_name='category_help')
    op.drop_index('user_id_idx', table_name='category_help')
    op.drop_table('category_help')
    op.drop_index('user_id_idx', table_name='billing')
    op.drop_table('billing')
    op.drop_index('brand_id_idx', table_name='product')
    op.drop_index('company_id_idx', table_name='product')
    op.drop_index('discount_id_idx', table_name='product')
    op.drop_index('model_cat_id_idx', table_name='product')
    op.drop_index('user_id_idx', table_name='product')
    op.drop_table('product')
    op.drop_table('sf_guard_user_permission')
    op.drop_index('product_id_idx', table_name='offer')
    op.drop_index('user_id_idx', table_name='offer')
    op.drop_table('offer')
    op.drop_index('user_id_idx', table_name='type_email')
    op.drop_table('type_email')
    op.drop_index('category_id_idx', table_name='category')
    op.drop_index('category_sluggable_idx', table_name='category')
    op.drop_index('user_id_idx', table_name='category')
    op.drop_table('category')
    op.drop_index('user_id_idx', table_name='discount')
    op.drop_table('discount')
    op.drop_index('attribute_id_idx', table_name='term')
    op.drop_index('term_sluggable_idx', table_name='term')
    op.drop_index('user_id_idx', table_name='term')
    op.drop_table('term')
    op.drop_index('brand_sluggable_idx', table_name='brand')
    op.drop_index('user_id_idx', table_name='brand')
    op.drop_table('brand')
    op.drop_index('user_id_idx', table_name='purchase')
    op.drop_table('purchase')
    op.drop_table('wpsnk_termmeta')
    op.drop_index('user_id_idx', table_name='company')
    op.drop_table('company')
    op.drop_index('collaboration_sluggable_idx', table_name='collaboration')
    op.drop_index('user_id_idx', table_name='collaboration')
    op.drop_table('collaboration')
    op.drop_index('category_id_idx', table_name='category_has_product')
    op.drop_index('product_id_idx', table_name='category_has_product')
    op.drop_table('category_has_product')
    op.drop_index('user_login_key', table_name='wpsnk_users')
    op.drop_table('wpsnk_users')
    op.drop_index('name', table_name='sf_guard_permission')
    op.drop_table('sf_guard_permission')
    op.drop_index('type_status_date', table_name='wpsnk_posts')
    op.drop_table('wpsnk_posts')
    op.drop_table('wpsnk_postmeta')
    op.drop_index('object_id', table_name='wpsnk_yoast_seo_meta')
    op.drop_table('wpsnk_yoast_seo_meta')
    op.drop_index('email_address', table_name='sf_guard_user')
    op.drop_index('is_active_idx_idx', table_name='sf_guard_user')
    op.drop_index('role_id_idx', table_name='sf_guard_user')
    op.drop_index('sf_guard_user_sluggable_idx', table_name='sf_guard_user')
    op.drop_index('username', table_name='sf_guard_user')
    op.drop_table('sf_guard_user')
    op.drop_index('company_id_idx', table_name='email')
    op.drop_index('type_email_id_idx', table_name='email')
    op.drop_index('user_id_idx', table_name='email')
    op.drop_table('email')
    op.drop_table('wpsnk_links')
    op.drop_table('wpsnk_terms')
    op.drop_index('user_id_idx', table_name='banner')
    op.drop_table('banner')
    op.drop_table('country')
    op.drop_index('company_id_idx', table_name='shipping')
    op.drop_index('user_id_idx', table_name='shipping')
    op.drop_table('shipping')
    op.drop_index('id', table_name='product2')
    op.drop_table('product2')
    op.drop_index('option_name', table_name='wpsnk_options')
    op.drop_table('wpsnk_options')
    op.drop_index('company_id_idx', table_name='prodx')
    op.drop_index('discount_id_idx', table_name='prodx')
    op.drop_index('product_sluggable_idx', table_name='prodx')
    op.drop_index('user_id_idx', table_name='prodx')
    op.drop_table('prodx')
    op.create_unique_constraint(None, 'product_detail', ['id'])
    op.alter_column('sizes_shoes', 'cm',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=True)
    op.alter_column('sizes_shoes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('sizes_shoes', 'europe',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=True)
    op.alter_column('sizes_shoes', 'inch',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=True)
    op.alter_column('sizes_shoes', 'sizes_types_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('sizes_shoes', 'uk',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('sizes_shoes', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('sizes_shoes', 'us',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('sizes_shoes', 'user_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
    op.drop_index('brand_id_idx', table_name='sizes_shoes')
    op.drop_index('user_id_idx', table_name='sizes_shoes')
    op.create_unique_constraint(None, 'sizes_shoes', ['id'])
    op.drop_constraint('sizes_shoes_brand_id_brand_id', 'sizes_shoes', type_='foreignkey')
    op.drop_constraint('sizes_shoes_user_id_sf_guard_user_id', 'sizes_shoes', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('sizes_shoes_user_id_sf_guard_user_id', 'sizes_shoes', 'sf_guard_user', ['user_id'], ['id'])
    op.create_foreign_key('sizes_shoes_brand_id_brand_id', 'sizes_shoes', 'brand', ['brand_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'sizes_shoes', type_='unique')
    op.create_index('user_id_idx', 'sizes_shoes', ['user_id'], unique=False)
    op.create_index('brand_id_idx', 'sizes_shoes', ['brand_id'], unique=False)
    op.alter_column('sizes_shoes', 'user_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
    op.alter_column('sizes_shoes', 'us',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('sizes_shoes', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('sizes_shoes', 'uk',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('sizes_shoes', 'sizes_types_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('sizes_shoes', 'inch',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=False)
    op.alter_column('sizes_shoes', 'europe',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=False)
    op.alter_column('sizes_shoes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('sizes_shoes', 'cm',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=False)
    op.drop_constraint(None, 'product_detail', type_='unique')
    op.create_table('prodx',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('discount_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('position', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('brand_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('brand_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('model_cat_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('model_cat', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('brief_description', mysql.TEXT(), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('visit', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('sale', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('expires_at', sa.DATE(), nullable=True),
    sa.Column('keywords', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('image0', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('image1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('image2', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('image3', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('image4', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('image5', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sku', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('stock', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('stock_min', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('stars', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('price', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('regular_price', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('weight', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('length', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('width', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('height', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('type_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('seo_title', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('seo_description', mysql.VARCHAR(length=160), nullable=True),
    sa.Column('seo_keywords', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='product_company_id_company_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], name='product_discount_id_discount_id'),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='product_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'prodx', ['user_id'], unique=False)
    op.create_index('product_sluggable_idx', 'prodx', ['slug', 'name'], unique=True)
    op.create_index('discount_id_idx', 'prodx', ['discount_id'], unique=False)
    op.create_index('company_id_idx', 'prodx', ['company_id'], unique=False)
    op.create_table('wpsnk_options',
    sa.Column('option_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('option_name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=191), server_default=sa.text("''"), nullable=False),
    sa.Column('option_value', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('autoload', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'yes'"), nullable=False),
    sa.PrimaryKeyConstraint('option_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('option_name', 'wpsnk_options', ['option_name'], unique=True)
    op.create_table('product2',
    sa.Column('id', mysql.INTEGER(display_width=10), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.INTEGER(display_width=10), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('shape1', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=10), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.VARCHAR(length=50), server_default=sa.text("'2019-11-20 00:00:00'"), nullable=False),
    sa.Column('updated_at', mysql.VARCHAR(length=50), server_default=sa.text("'2019-11-20 00:00:00'"), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'product2', ['id'], unique=True)
    op.create_table('shipping',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('price', mysql.FLOAT(precision=18, scale=4), nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('status', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='shipping_company_id_company_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='shipping_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'shipping', ['user_id'], unique=False)
    op.create_index('company_id_idx', 'shipping', ['company_id'], unique=False)
    op.create_table('country',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('language', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('currency', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('currency_symbol', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('flag', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('banner',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('order_front', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('category_votes_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('position', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='banner_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'banner', ['user_id'], unique=False)
    op.create_table('wpsnk_terms',
    sa.Column('term_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('term_group', mysql.BIGINT(display_width=10), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('term_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wpsnk_links',
    sa.Column('link_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('link_url', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('link_name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('link_image', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('link_target', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=25), server_default=sa.text("''"), nullable=False),
    sa.Column('link_description', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('link_visible', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'Y'"), nullable=False),
    sa.Column('link_owner', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('link_rating', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('link_updated', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('link_rel', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('link_notes', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('link_rss', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('link_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('email',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('copy', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('type_email_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=4), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('locked', mysql.TINYINT(display_width=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='email_company_id_company_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_email_id'], ['type_email.id'], name='email_type_email_id_type_email_id'),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='email_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'email', ['user_id'], unique=False)
    op.create_index('type_email_id_idx', 'email', ['type_email_id'], unique=False)
    op.create_index('company_id_idx', 'email', ['company_id'], unique=False)
    op.create_table('sf_guard_user',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('oauth_provider', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('oauth_uid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('biography', mysql.TEXT(), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('address2', mysql.TEXT(), nullable=True),
    sa.Column('languages', mysql.TEXT(), nullable=True),
    sa.Column('code_phone', mysql.TEXT(), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('gender_other', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('civil_status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('code_country', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('company_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('occupation', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('algorithm', mysql.VARCHAR(length=128), server_default=sa.text("'sha1'"), nullable=False),
    sa.Column('salt', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('formatted_address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('viewport', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('route', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('street_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('postal_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('locality', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('country_short', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('administrative_area_level_1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('google_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_shop', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_email', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_phone', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_google', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_facebook', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('is_super_admin', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('notify_email', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('notify_activity', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('notify_reserva', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('conect_social', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('contact_import', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('advertising', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('observation', mysql.TEXT(), nullable=True),
    sa.Column('shop_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shop_image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shop_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shop_bio', mysql.TEXT(), nullable=True),
    sa.Column('shop_shipping', mysql.TEXT(), nullable=True),
    sa.Column('shop_return', mysql.TEXT(), nullable=True),
    sa.Column('instagram', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('twitter', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('facebook', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('youtube', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='sf_guard_user_role_id_role_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'sf_guard_user', ['username'], unique=True)
    op.create_index('sf_guard_user_sluggable_idx', 'sf_guard_user', ['slug', 'id'], unique=True)
    op.create_index('role_id_idx', 'sf_guard_user', ['role_id'], unique=False)
    op.create_index('is_active_idx_idx', 'sf_guard_user', ['is_active'], unique=False)
    op.create_index('email_address', 'sf_guard_user', ['email_address'], unique=True)
    op.create_table('wpsnk_yoast_seo_meta',
    sa.Column('object_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('internal_link_count', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('incoming_link_count', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('object_id', 'wpsnk_yoast_seo_meta', ['object_id'], unique=True)
    op.create_table('wpsnk_postmeta',
    sa.Column('meta_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('meta_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=True),
    sa.Column('meta_value', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('meta_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('wpsnk_posts',
    sa.Column('ID', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('post_author', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('post_date', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('post_date_gmt', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('post_content', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('post_title', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('post_excerpt', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('post_status', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'publish'"), nullable=False),
    sa.Column('comment_status', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('ping_status', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('post_password', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('post_name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('to_ping', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('pinged', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('post_modified', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('post_modified_gmt', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('post_content_filtered', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('post_parent', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('guid', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('menu_order', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('post_type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'post'"), nullable=False),
    sa.Column('post_mime_type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('comment_count', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('type_status_date', 'wpsnk_posts', ['post_type', 'post_status', 'post_date', 'ID'], unique=False)
    op.create_table('sf_guard_permission',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('detalles', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'sf_guard_permission', ['name'], unique=True)
    op.create_table('wpsnk_users',
    sa.Column('ID', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_login', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('user_pass', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('user_nicename', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('user_email', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('user_url', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('user_registered', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('user_activation_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('user_status', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('display_name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=250), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_login_key', 'wpsnk_users', ['user_login'], unique=False)
    op.create_table('category_has_product',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('category_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='category_has_product_category_id_category_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['prodx.id'], name='category_has_product_product_id_product_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('product_id_idx', 'category_has_product', ['product_id'], unique=False)
    op.create_index('category_id_idx', 'category_has_product', ['category_id'], unique=False)
    op.create_table('collaboration',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('seo_title', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('seo_description', mysql.VARCHAR(length=160), nullable=True),
    sa.Column('seo_keywords', mysql.TEXT(), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('favicon', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('status', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('posicion_order', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='collaboration_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'collaboration', ['user_id'], unique=False)
    op.create_index('collaboration_sluggable_idx', 'collaboration', ['slug', 'name'], unique=True)
    op.create_table('company',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fax', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('sitio_web', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('observation', mysql.TEXT(), nullable=True),
    sa.Column('bio', mysql.TEXT(), nullable=True),
    sa.Column('shipping_policy', mysql.TEXT(), nullable=True),
    sa.Column('return_policy', mysql.TEXT(), nullable=True),
    sa.Column('privacy_policy', mysql.TEXT(), nullable=True),
    sa.Column('top_bar', mysql.TEXT(), nullable=True),
    sa.Column('banner', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('instagram', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('twitter', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('facebook', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('youtube', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('image1', mysql.INTEGER(display_width=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='company_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'company', ['user_id'], unique=False)
    op.create_table('wpsnk_termmeta',
    sa.Column('meta_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('term_id', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('meta_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=True),
    sa.Column('meta_value', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('meta_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('purchase',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('coin_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('type_payment_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('taxes', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('conditions', mysql.TEXT(), nullable=True),
    sa.Column('observation', mysql.TEXT(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('expires_at', sa.DATE(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('total_quantity', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('total_price', mysql.FLOAT(precision=18, scale=4), nullable=False),
    sa.Column('amount_paid', mysql.FLOAT(precision=18, scale=4), nullable=False),
    sa.Column('discount', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='purchase_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'purchase', ['user_id'], unique=False)
    op.create_table('brand',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('brand_id', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('seo_title', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('seo_description', mysql.VARCHAR(length=160), nullable=True),
    sa.Column('seo_keywords', mysql.TEXT(), nullable=True),
    sa.Column('shortcut', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('favicon', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('status', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rep_popular_brand', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('posicion_order', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='brand_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'brand', ['user_id'], unique=False)
    op.create_index('brand_sluggable_idx', 'brand', ['slug', 'name'], unique=True)
    op.create_table('term',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('attribute_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('status', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], name='term_attribute_id_attribute_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='term_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'term', ['user_id'], unique=False)
    op.create_index('term_sluggable_idx', 'term', ['slug', 'name'], unique=True)
    op.create_index('attribute_id_idx', 'term', ['attribute_id'], unique=False)
    op.create_table('discount',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('price', mysql.FLOAT(precision=18, scale=4), nullable=False),
    sa.Column('expires_at', sa.DATE(), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('status', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='discount_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'discount', ['user_id'], unique=False)
    op.create_table('category',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('category_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('seo_title', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('seo_description', mysql.VARCHAR(length=160), nullable=True),
    sa.Column('seo_keywords', mysql.TEXT(), nullable=True),
    sa.Column('shortcut', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('favicon', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('status', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('posicion_order', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='category_category_id_category_id'),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='category_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'category', ['user_id'], unique=False)
    op.create_index('category_sluggable_idx', 'category', ['slug', 'name'], unique=True)
    op.create_index('category_id_idx', 'category', ['category_id'], unique=False)
    op.create_table('type_email',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='type_email_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'type_email', ['user_id'], unique=False)
    op.create_table('offer',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('order_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('size', mysql.FLOAT(precision=18, scale=2), nullable=False),
    sa.Column('product_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('product_name', mysql.TEXT(), nullable=False),
    sa.Column('product_image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sku', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('coin_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('type_payment_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('taxes', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('conditions', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('box', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('damaged_box', mysql.VARCHAR(length=20), server_default=sa.text("'0'"), nullable=False),
    sa.Column('observation', mysql.TEXT(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('expires_at', sa.DATE(), nullable=True),
    sa.Column('total_quantity', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('amount_offer', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('trasaction_fee', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('trasaction_fee_amount', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('payment_proc_fee', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('payment_proc_fee_amount', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('discount', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('security_ip', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='offer_product_id_product_id'),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='offer_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'offer', ['user_id'], unique=False)
    op.create_index('product_id_idx', 'offer', ['product_id'], unique=False)
    op.create_table('sf_guard_user_permission',
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['sf_guard_permission.id'], name='sf_guard_user_permission_permission_id_sf_guard_permission_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='sf_guard_user_permission_user_id_sf_guard_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('product',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('discount_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('position', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('brand_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('brand_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('model_cat_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('model_cat', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('brief_description', mysql.TEXT(), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('visit', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('sale', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('expires_at', sa.DATE(), nullable=True),
    sa.Column('keywords', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shape1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shape2', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shape3', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shape4', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shape5', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shape6', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shape7', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shape8', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_box', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_lateral', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_medial', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_heel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_top', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_soles', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_tag', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sku', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('stock', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('stock_min', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('stars', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('price', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('regular_price', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('weight', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('length', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('width', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('height', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('type_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('seo_title', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('seo_description', mysql.VARCHAR(length=160), nullable=True),
    sa.Column('seo_keywords', mysql.TEXT(), nullable=True),
    sa.Column('shortcut', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('lowest_ask', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('highest_offer', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('most_recent', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('image0', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('image2', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('image3', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('image4', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('image5', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('image1', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'product', ['user_id'], unique=False)
    op.create_index('model_cat_id_idx', 'product', ['model_cat_id'], unique=False)
    op.create_index('discount_id_idx', 'product', ['discount_id'], unique=False)
    op.create_index('company_id_idx', 'product', ['company_id'], unique=False)
    op.create_index('brand_id_idx', 'product', ['brand_id'], unique=False)
    op.create_table('billing',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('bill_type_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('card_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('card_type', mysql.TEXT(), nullable=True),
    sa.Column('expiry', mysql.TEXT(), nullable=True),
    sa.Column('card_code', mysql.TEXT(), nullable=True),
    sa.Column('success', mysql.TEXT(), nullable=True),
    sa.Column('response_code', mysql.TEXT(), nullable=True),
    sa.Column('status_message', mysql.TEXT(), nullable=True),
    sa.Column('trans_id', mysql.TEXT(), nullable=True),
    sa.Column('approval_code', mysql.TEXT(), nullable=True),
    sa.Column('approval_message', mysql.TEXT(), nullable=True),
    sa.Column('avs_response', mysql.TEXT(), nullable=True),
    sa.Column('csc_response', mysql.TEXT(), nullable=True),
    sa.Column('masked_card_number', mysql.TEXT(), nullable=True),
    sa.Column('external_transaction_id', mysql.TEXT(), nullable=True),
    sa.Column('bill_phone', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bill_call', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bill_first_name', mysql.TEXT(), nullable=False),
    sa.Column('bill_last_name', mysql.TEXT(), nullable=False),
    sa.Column('bill_address', mysql.TEXT(), nullable=False),
    sa.Column('bill_address2', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bill_formatted_address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bill_viewport', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bill_route', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bill_street_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bill_postal_code', mysql.TEXT(), nullable=False),
    sa.Column('bill_city', mysql.TEXT(), nullable=False),
    sa.Column('bill_locality', mysql.TEXT(), nullable=False),
    sa.Column('bill_country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bill_country_short', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bill_administrative_area_level_1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('observation', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='billing_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'billing', ['user_id'], unique=False)
    op.create_table('category_help',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('category_help_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('seo_title', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('seo_description', mysql.VARCHAR(length=160), nullable=True),
    sa.Column('seo_keywords', mysql.TEXT(), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('favicon', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('status', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('posicion_order', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'category_help', ['user_id'], unique=False)
    op.create_index('category_help_sluggable_idx', 'category_help', ['slug', 'name'], unique=True)
    op.create_index('category_help_id_idx', 'category_help', ['category_help_id'], unique=False)
    op.create_table('contact',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('category_contact_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('answer', mysql.TEXT(), nullable=True),
    sa.Column('from_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('from_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=4), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='contact_company_id_company_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='contact_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'contact', ['user_id'], unique=False)
    op.create_index('company_id_idx', 'contact', ['company_id'], unique=False)
    op.create_index('category_contact_id_idx', 'contact', ['category_contact_id'], unique=False)
    op.create_table('wpsnk_term_taxonomy',
    sa.Column('term_taxonomy_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('term_id', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('taxonomy', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('description', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('parent', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('count', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('term_taxonomy_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('term_id_taxonomy', 'wpsnk_term_taxonomy', ['term_id', 'taxonomy'], unique=True)
    op.create_table('wpsnk_term_relationships',
    sa.Column('object_id', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('term_taxonomy_id', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('term_order', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('object_id', 'term_taxonomy_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sf_guard_group',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'sf_guard_group', ['name'], unique=True)
    op.create_table('sf_guard_forgot_password',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('unique_key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='sf_guard_forgot_password_user_id_sf_guard_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'sf_guard_forgot_password', ['user_id'], unique=False)
    op.create_table('wpsnk_yoast_seo_links',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('post_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('target_post_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('link_direction', 'wpsnk_yoast_seo_links', ['post_id', 'type'], unique=False)
    op.create_table('attribute',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('status', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='attribute_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'attribute', ['user_id'], unique=False)
    op.create_index('attribute_sluggable_idx', 'attribute', ['slug', 'name'], unique=True)
    op.create_table('detail',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('wpsnk_commentmeta',
    sa.Column('meta_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('comment_id', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('meta_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=True),
    sa.Column('meta_value', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('meta_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('order_resume',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('address2', mysql.TEXT(), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('code_country', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('company_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('email_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('formatted_address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('viewport', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('route', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('street_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('postal_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('locality', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('country_short', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('administrative_area_level_1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('shipping_first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shipping_last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shipping_address', mysql.TEXT(), nullable=True),
    sa.Column('shipping_address2', mysql.TEXT(), nullable=True),
    sa.Column('shipping_phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('shipping_code_country', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('shipping_country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_email_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shipping_formatted_address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_viewport', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_route', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_street_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_postal_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_locality', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_country_short', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_administrative_area_level_1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('quantity', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('price', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('observation', mysql.TEXT(), nullable=True),
    sa.Column('shop_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shop_image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shop_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shop_shipping', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shop_return', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['shipping_id'], ['shipping.id'], name='order_resume_shipping_id_shipping_id'),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='order_resume_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'order_resume', ['user_id'], unique=False)
    op.create_index('shipping_id_idx', 'order_resume', ['shipping_id'], unique=False)
    op.create_index('shipping_email_address', 'order_resume', ['shipping_email_address'], unique=True)
    op.create_index('email_address', 'order_resume', ['email_address'], unique=True)
    op.create_table('sf_guard_group_permission',
    sa.Column('group_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['sf_guard_group.id'], name='sf_guard_group_permission_group_id_sf_guard_group_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['sf_guard_permission.id'], name='sf_guard_group_permission_permission_id_sf_guard_permission_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'permission_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('model_cat',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('brand_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('model_cat_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('seo_title', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('seo_description', mysql.VARCHAR(length=160), nullable=True),
    sa.Column('seo_keywords', mysql.TEXT(), nullable=True),
    sa.Column('shortcut', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('favicon', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('status', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rep_popular_brand', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('posicion_order', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name='model_cat_brand_id_brand_id'),
    sa.ForeignKeyConstraint(['model_cat_id'], ['model_cat.id'], name='model_cat_model_cat_id_model_cat_id'),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='model_cat_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'model_cat', ['user_id'], unique=False)
    op.create_index('model_cat_sluggable_idx', 'model_cat', ['slug', 'name'], unique=True)
    op.create_index('model_cat_id_idx', 'model_cat', ['model_cat_id'], unique=False)
    op.create_index('brand_id_idx', 'model_cat', ['brand_id'], unique=False)
    op.create_table('sf_guard_remember_key',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('remember_key', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='sf_guard_remember_key_user_id_sf_guard_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'sf_guard_remember_key', ['user_id'], unique=False)
    op.create_table('ask',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('order_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('size', mysql.FLOAT(precision=18, scale=2), nullable=False),
    sa.Column('product_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('product_name', mysql.TEXT(), nullable=False),
    sa.Column('product_image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sku', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('coin_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('type_payment_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('taxes', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('conditions', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('box', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('damaged_box', mysql.VARCHAR(length=20), server_default=sa.text("'0'"), nullable=False),
    sa.Column('observation', mysql.TEXT(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('expires_at', sa.DATE(), nullable=True),
    sa.Column('total_quantity', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('payout_amount', mysql.FLOAT(precision=18, scale=2), nullable=False),
    sa.Column('amount_ask', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('trasaction_fee', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('trasaction_fee_amount', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('payment_proc_fee', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('payment_proc_fee_amount', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('discount', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('security_ip', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_box', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_lateral', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_medial', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_heel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_top', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_soles', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('img_tag', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='ask_product_id_product_id'),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='ask_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'ask', ['user_id'], unique=False)
    op.create_index('product_id_idx', 'ask', ['product_id'], unique=False)
    op.create_table('wpsnk_comments',
    sa.Column('comment_ID', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('comment_post_ID', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('comment_author', mysql.TINYTEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('comment_author_email', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('comment_author_url', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('comment_author_IP', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('comment_date', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('comment_date_gmt', mysql.DATETIME(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('comment_content', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('comment_karma', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('comment_approved', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("'1'"), nullable=False),
    sa.Column('comment_agent', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('comment_type', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), server_default=sa.text("''"), nullable=False),
    sa.Column('comment_parent', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('comment_ID'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('comment_approved_date_gmt', 'wpsnk_comments', ['comment_approved', 'comment_date_gmt'], unique=False)
    op.create_table('order_item',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('order_resume_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('shop', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('shop_image', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('salt', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('quantity', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('price', mysql.FLOAT(precision=18, scale=4), nullable=True),
    sa.Column('observation', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['order_resume_id'], ['order_resume.id'], name='order_item_order_resume_id_order_resume_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='order_item_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'order_item', ['user_id'], unique=False)
    op.create_index('order_resume_id_idx', 'order_item', ['order_resume_id'], unique=False)
    op.create_table('wpsnk_usermeta',
    sa.Column('umeta_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('meta_key', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=True),
    sa.Column('meta_value', mysql.LONGTEXT(collation='utf8mb4_unicode_520_ci'), nullable=True),
    sa.PrimaryKeyConstraint('umeta_id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('category_contact',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='category_contact_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'category_contact', ['user_id'], unique=False)
    op.create_table('sf_guard_user_group',
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['sf_guard_group.id'], name='sf_guard_user_group_group_id_sf_guard_group_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='sf_guard_user_group_user_id_sf_guard_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('role_has_detail',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('role_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('detail_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['detail_id'], ['detail.id'], name='role_has_detail_detail_id_detail_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='role_has_detail_role_id_role_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('role_id_idx', 'role_has_detail', ['role_id'], unique=False)
    op.create_index('detail_id_idx', 'role_has_detail', ['detail_id'], unique=False)
    op.create_table('question_answer',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('category_help_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('question', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('answer', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('status', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('posicion_order', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'question_answer', ['user_id'], unique=False)
    op.create_index('category_help_id_idx', 'question_answer', ['category_help_id'], unique=False)
    op.create_table('role',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sell',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('order_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('size', mysql.FLOAT(precision=18, scale=2), nullable=False),
    sa.Column('product_name', mysql.TEXT(), nullable=False),
    sa.Column('product_image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sku', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('coin_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('type_payment_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('taxes', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('conditions', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('box', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('damaged_box', mysql.VARCHAR(length=20), server_default=sa.text("'0'"), nullable=False),
    sa.Column('observation', mysql.TEXT(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('expires_at', sa.DATE(), nullable=True),
    sa.Column('total_quantity', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('payout_amount', mysql.FLOAT(precision=18, scale=2), nullable=False),
    sa.Column('amount_sell', mysql.FLOAT(precision=18, scale=2), nullable=False),
    sa.Column('trasaction_fee', mysql.FLOAT(precision=18, scale=2), nullable=False),
    sa.Column('trasaction_fee_amount', mysql.FLOAT(precision=18, scale=2), nullable=False),
    sa.Column('payment_proc_fee', mysql.FLOAT(precision=18, scale=2), nullable=False),
    sa.Column('payment_proc_fee_amount', mysql.FLOAT(precision=18, scale=2), nullable=False),
    sa.Column('discount', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=4), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sf_guard_user.id'], name='sell_user_id_sf_guard_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_idx', 'sell', ['user_id'], unique=False)
    # ### end Alembic commands ###
