"""empty message

Revision ID: b9932f88c61e
Revises: 
Create Date: 2020-05-14 16:34:06.423379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9932f88c61e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('category_help_id_idx', table_name='category_help')
    op.drop_index('category_help_sluggable_idx', table_name='category_help')
    op.drop_table('category_help')
    op.drop_index('detail_id_idx', table_name='role_has_detail')
    op.drop_index('role_id_idx', table_name='role_has_detail')
    op.drop_table('role_has_detail')
    op.drop_table('deparment')
    op.drop_table('notification')
    op.drop_table('transaction')
    op.drop_table('detail')
    op.drop_table('email')
    op.drop_index('email_address', table_name='users')
    op.drop_table('users')
    op.drop_table('user_notification')
    op.drop_table('failed_jobs')
    op.drop_table('role')
    op.drop_table('verification')
    op.drop_index('slug', table_name='category')
    op.drop_table('category')
    op.drop_index('category_help_id_idx', table_name='question_answer')
    op.drop_table('question_answer')
    op.drop_table('migrations')
    op.drop_index('email_address', table_name='customer')
    op.drop_index('username', table_name='customer')
    op.drop_table('customer')
    op.drop_table('posts')
    op.drop_table('help_desk')
    op.drop_index('category_id_idx', table_name='category_has_product')
    op.drop_index('product_id_idx', table_name='category_has_product')
    op.drop_table('category_has_product')
    op.drop_index('ask_id', table_name='match')
    op.drop_index('offer_id', table_name='match')
    op.drop_table('match')
    op.drop_index('password_resets_email_index', table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index('fk_deal_transaction1_idx', table_name='deal')
    op.drop_table('deal')
    op.alter_column('brand', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('brand', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('brand', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('brand', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.drop_index('slug', table_name='brand')
    op.create_unique_constraint(None, 'brand', ['id'])
    op.drop_constraint('users_id', 'brand', type_='foreignkey')
    op.alter_column('media_storage', 'product_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('media_storage', 'url',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'media_storage', ['id'])
    op.drop_constraint('transaction_id', 'media_storage', type_='foreignkey')
    op.drop_constraint('fk_media_storage_verification1', 'media_storage', type_='foreignkey')
    op.alter_column('model_cat', 'brand_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('model_cat', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('model_cat', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('model_cat', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('model_cat', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.drop_index('slug', table_name='model_cat')
    op.create_unique_constraint(None, 'model_cat', ['id'])
    op.drop_constraint('model_cat_model_cat_id_model_cat_id', 'model_cat', type_='foreignkey')
    op.drop_constraint('fk_model_cat_user1', 'model_cat', type_='foreignkey')
    op.alter_column('product', 'brand_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('product', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('product', 'model_cat_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('product', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('product', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('product', 'visit',
               existing_type=mysql.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index('slug', table_name='product')
    op.create_unique_constraint(None, 'product', ['id'])
    op.drop_constraint('fk_product_user1', 'product', type_='foreignkey')
    op.alter_column('product_detail', 'product_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('product_detail', 'sizes_shoes_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'product_detail', ['id'])
    op.drop_constraint('product_detail_sizes_shoes_id_sizes_shoes_id', 'product_detail', type_='foreignkey')
    op.drop_constraint('product_detail_product_id_product_id', 'product_detail', type_='foreignkey')
    op.create_foreign_key(None, 'product_detail', 'sizes_shoes', ['sizes_shoes_id'], ['id'])
    op.create_foreign_key(None, 'product_detail', 'product', ['product_id'], ['id'])
    op.alter_column('sizes_shoes', 'brand_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('sizes_shoes', 'cm',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=True)
    op.alter_column('sizes_shoes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('sizes_shoes', 'europe',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=True)
    op.alter_column('sizes_shoes', 'inch',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=True)
    op.alter_column('sizes_shoes', 'sizes_types_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('sizes_shoes', 'uk',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('sizes_shoes', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('sizes_shoes', 'us',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('sizes_shoes', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'sizes_shoes', ['id'])
    op.drop_constraint('fk_sizes_shoes_user1', 'sizes_shoes', type_='foreignkey')
    op.drop_constraint('sizes_shoes_brand_id_brand_id', 'sizes_shoes', type_='foreignkey')
    op.create_foreign_key(None, 'sizes_shoes', 'brand', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sizes_shoes', type_='foreignkey')
    op.create_foreign_key('sizes_shoes_brand_id_brand_id', 'sizes_shoes', 'brand', ['brand_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_sizes_shoes_user1', 'sizes_shoes', 'users', ['users_id'], ['id'])
    op.drop_constraint(None, 'sizes_shoes', type_='unique')
    op.alter_column('sizes_shoes', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('sizes_shoes', 'us',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('sizes_shoes', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('sizes_shoes', 'uk',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('sizes_shoes', 'sizes_types_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('sizes_shoes', 'inch',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=False)
    op.alter_column('sizes_shoes', 'europe',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=False)
    op.alter_column('sizes_shoes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('sizes_shoes', 'cm',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=False)
    op.alter_column('sizes_shoes', 'brand_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'product_detail', type_='foreignkey')
    op.drop_constraint(None, 'product_detail', type_='foreignkey')
    op.create_foreign_key('product_detail_product_id_product_id', 'product_detail', 'product', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('product_detail_sizes_shoes_id_sizes_shoes_id', 'product_detail', 'sizes_shoes', ['sizes_shoes_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'product_detail', type_='unique')
    op.alter_column('product_detail', 'sizes_shoes_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('product_detail', 'product_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.create_foreign_key('fk_product_user1', 'product', 'users', ['users_id'], ['id'])
    op.drop_constraint(None, 'product', type_='unique')
    op.create_index('slug', 'product', ['slug', 'name'], unique=True)
    op.alter_column('product', 'visit',
               existing_type=mysql.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('product', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('product', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('product', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('product', 'model_cat_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('product', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('product', 'brand_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.create_foreign_key('fk_model_cat_user1', 'model_cat', 'users', ['users_id'], ['id'])
    op.create_foreign_key('model_cat_model_cat_id_model_cat_id', 'model_cat', 'model_cat', ['model_cat_id'], ['id'])
    op.drop_constraint(None, 'model_cat', type_='unique')
    op.create_index('slug', 'model_cat', ['slug', 'name'], unique=True)
    op.alter_column('model_cat', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('model_cat', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('model_cat', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('model_cat', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('model_cat', 'brand_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.create_foreign_key('fk_media_storage_verification1', 'media_storage', 'verification', ['verification_id'], ['id'])
    op.create_foreign_key('transaction_id', 'media_storage', 'transaction', ['transaction_id'], ['id'])
    op.drop_constraint(None, 'media_storage', type_='unique')
    op.alter_column('media_storage', 'url',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('media_storage', 'product_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.create_foreign_key('users_id', 'brand', 'users', ['users_id'], ['id'])
    op.drop_constraint(None, 'brand', type_='unique')
    op.create_index('slug', 'brand', ['slug', 'name'], unique=True)
    op.alter_column('brand', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('brand', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('brand', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('brand', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_table('deal',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('conditions', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('box', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('product_detail_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('type_transaction', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('images', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('transactioncol', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('transaction_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_detail_id'], ['product_detail.id'], name='fk_offer_product_detail10'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name='fk_deal_transaction1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_deal_transaction1_idx', 'deal', ['transaction_id'], unique=False)
    op.create_table('password_resets',
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True)
    )
    op.create_index('password_resets_email_index', 'password_resets', ['email'], unique=False)
    op.create_table('match',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('offer_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ask_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('label', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('tracking_seller', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('tracking_buyer', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('images', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['ask_id'], ['transaction.id'], name='fk_offer_has_offer_offer2'),
    sa.ForeignKeyConstraint(['offer_id'], ['transaction.id'], name='fk_offer_has_offer_offer1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('offer_id', 'match', ['ask_id'], unique=False)
    op.create_index('ask_id', 'match', ['offer_id'], unique=False)
    op.create_table('category_has_product',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='category_has_product_category_id_category_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='category_has_product_product_id_product_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('product_id_idx', 'category_has_product', ['product_id'], unique=False)
    op.create_index('category_id_idx', 'category_has_product', ['category_id'], unique=False)
    op.create_table('help_desk',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('deparment_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('customer_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('answer', mysql.TEXT(), nullable=True),
    sa.Column('from_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('from_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='fk_contact_customer1'),
    sa.ForeignKeyConstraint(['deparment_id'], ['deparment.id'], name='contact_category_contact_id_category_contact_id'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='fk_contact_user1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('body', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('oauth_provider', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('oauth_uid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('biography', mysql.TEXT(), nullable=True),
    sa.Column('code_phone', mysql.TEXT(), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('code_country', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('email_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('salt', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('formatted_address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('viewport', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('route', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('street_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('postal_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('locality', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('country_short', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('administrative_area_level_1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_email', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_phone', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_google', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_facebook', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('instagram', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('twitter', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('facebook', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('youtube', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('username', 'customer', ['username'], unique=True)
    op.create_index('email_address', 'customer', ['email_address'], unique=True)
    op.create_table('migrations',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('migration', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('batch', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_answer',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('category_help_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('question', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('answer', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('posicion_order', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['category_help_id'], ['category_help.id'], name='question_answer_category_help_id_category_help_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('category_help_id_idx', 'question_answer', ['category_help_id'], unique=False)
    op.create_table('category',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('seo_title', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('seo_description', mysql.VARCHAR(length=160), nullable=True),
    sa.Column('seo_keywords', mysql.TEXT(), nullable=True),
    sa.Column('shortcut', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('favicon', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('posicion_order', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='category_category_id_category_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('slug', 'category', ['slug', 'name'], unique=True)
    op.create_table('verification',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('observation', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('match_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], name='fk_verification_match1'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='fk_verification_user1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failed_jobs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('connection', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('queue', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('payload', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('exception', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('failed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notification',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('customer_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('notification_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_active_num', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='customer_id'),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], name='notification_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email_verified_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('remember_token', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='fk_users_role1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('email_address', 'users', ['email'], unique=True)
    op.create_table('email',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('copy', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='fk_email_user1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('order_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('exchange_rate', mysql.FLOAT(precision=18, scale=2), nullable=False),
    sa.Column('conditions', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('box', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('damaged_box', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('expires_at', sa.DATE(), nullable=True),
    sa.Column('amount', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('trasaction_fee', mysql.FLOAT(precision=18, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('payment_proc_fee', mysql.FLOAT(precision=18, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('discount', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('ip_address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('browser', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('device', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('customer_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('product_detail_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('type_transaction', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('transactioncol', mysql.VARCHAR(length=45), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='fk_offer_customer1'),
    sa.ForeignKeyConstraint(['product_detail_id'], ['product_detail.id'], name='fk_offer_product_detail1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('email_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type_notification', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], name='fk_notification_email1'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='fk_notification_user1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deparment',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='fk_category_contact_user1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_has_detail',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('detail_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['detail_id'], ['detail.id'], name='role_has_detail_detail_id_detail_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='role_has_detail_role_id_role_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('role_id_idx', 'role_has_detail', ['role_id'], unique=False)
    op.create_index('detail_id_idx', 'role_has_detail', ['detail_id'], unique=False)
    op.create_table('category_help',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('category_help_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('seo_title', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('seo_description', mysql.VARCHAR(length=160), nullable=True),
    sa.Column('seo_keywords', mysql.TEXT(), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('favicon', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('posicion_order', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_help_id'], ['category_help.id'], name='category_help_category_help_id_category_help_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('category_help_sluggable_idx', 'category_help', ['slug', 'name'], unique=True)
    op.create_index('category_help_id_idx', 'category_help', ['category_help_id'], unique=False)
    # ### end Alembic commands ###
